Remove deprecated class map generator documentation
zendframework/zend-loader pull request #19
Opened 2019-11-06 21:34 UTC by arueckauer

This PR removes the documentation of the ZF 2 script `bin/classmap_generator.php`, which never was part of this component.

Instead the usage of Composer for autoloading is suggested and a reference to the migration guide added.

2019-11-07 18:41 UTC, froschdesign commented
@weierophinney @michalbundyra
Is the `Zend\Loader\ClassMapAutoloader` deprecated or can this class be marked as deprecated?

2019-11-07 18:52 UTC, weierophinney commented
Honestly, this entire package can likely be deprecated.

The only places it is used anywhere within ZF are:

- zend-modulemanager (which uses the `ModuleAutoloader` as a fallback to the application autoloader)
- zend-http (which uses the `PluginClassLoader` for loading HTTP header implementations, and should likely move to a standard plugin manager, but instead is going to be eventually deprecated in favor of Diactoros anyways)

In short: I don't know that we need to deprecate anything; it's more likely that we'll abandon it after the move to Laminas, in favor of inlining those facilities into the packages that use them currently.

2019-11-07 19:46 UTC, froschdesign commented
@weierophinney 
> zend-modulemanager (which uses the `ModuleAutoloader` as a fallback to the application autoloader)

And there is already a pull request to drop zend-loader: https://github.com/zendframework/zend-modulemanager/pull/78 😃 

> …it's more likely that we'll abandon it after the move to Laminas…

Okay, that's the information we need here. Thanks!

2019-11-07 20:01 UTC, froschdesign requested changes
Only two minor changes are needed.

(We refuse all other adjustments here, like missing array example for `ClassMapAutoloader` or a separate migration section.)

2019-11-08 04:45 UTC, arueckauer commented on docs/book/class-map-autoloader.md
> +The first step is to generate a class map file in form of a PHP file returning an
Done.

2019-11-08 04:45 UTC, arueckauer commented on docs/book/classmap-generator.md
> +The script `bin/classmap_generator.php` has been removed and is no longer available. Instead, we recommend using [Composer for autoloading](https://getcomposer.org/doc/04-schema.md#autoload).
Done.

2019-11-08 13:34 UTC, froschdesign approved these changes

2019-11-08 14:25 UTC, michalbundyra commented
Thanks, @arueckauer!

2019-11-08 14:25 UTC, merged